# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.04.23
_src_path: gh:scientific-python/cookie
backend: maturin
email: lucas.colley8@gmail.com
full_name: Lucas Colley
license: MIT
org: lucascolley
project_name: pyo3-array
project_short_description: An experimental Python API for rust-ndarray, following
    the Python array API standard.
url: https://github.com/lucascolley/pyo3-array
